### PR TITLE
Fixes for non-local JAR loading and generator when using Maven plugin.

### PR DESCRIPTION
**Pull request by hendrikvanantwerpen**
* Use VFS2's own method to get local files (or local copies) and use this to load JARs from inside archives.
 * Add MavenBuild options to generator, to prevent it from generating POM, Eclipse specific files when a build done with the Maven plugin.

### CODE REVIEW

**Comment by Gohla** [comment]
I still need the local file provider stuff in Eclipse. Eclipse resources are under the eclipse:// file system, but sometimes I need to convert them to the file:// file system, and I'd like to do so without copying them. The replicateFile method will always copy files that are not on the file:// file system, right?

What about keeping the local file provider stuff, but replicating the file as a last resort? In that case localFile will not create a copy for file:// and eclipse:// resources, but it will for others.

**Comment by hendrikvanantwerpen** [comment]
The `replicateFile` documentation [1] suggests the file will only be copied if it is not already local. From looking at the VFS `LocalFileSystem` implementation, a filesystem can override the `doReplicateFile` method to just return the `File` object instead of using the default copy mechanism. I think you can do the same in `EclipseResourceFileSystem` and then the files will not be copied.

[1] https://commons.apache.org/proper/commons-vfs/apidocs/org/apache/commons/vfs2/FileSystem.html#replicateFile%28org.apache.commons.vfs2.FileObject,%20org.apache.commons.vfs2.FileSelector%29

[2] https://svn.apache.org/viewvc/commons/proper/vfs/trunk/core/src/main/java/org/apache/commons/vfs2/provider/local/LocalFileSystem.java?view=markup

**Comment by Gohla** [comment]
Ah, I didn't know that was extensible, I'll use that instead then :)

**Comment by Gohla** [comment]
Since I cannot add any commits to your repo, I will merge it (and break stuff) and apply fixes afterwards. Also your latest commit looks like a code clone, could you fix that in a subsequent PR?

**Pull request merged**
