### PR TITLE
Remove typesmart

### PR DESCRIPTION
**Pull request by Apanatshka**
Merge must be synchronized with other PRs. PR group:

https://github.com/metaborg/stratego/pull/8
https://github.com/metaborg/spt/pull/27
https://github.com/metaborg/spoofax-eclipse/pull/17
https://github.com/metaborg/spoofax/pull/63
https://github.com/metaborg/spg/pull/4
https://github.com/metaborg/spoofax-deploy/pull/27
https://github.com/metaborg/mb-rep/pull/19
https://github.com/metaborg/jsglr/pull/78
https://github.com/metaborg/dynsem/pull/172
https://github.com/metaborg/flowspec/pull/4

### CODE REVIEW

**Comment by Apanatshka** [comment]
@Gohla do you think we should refactor the term factory service further? The two get methods are now the same as getGeneric. If we replace the get methods everywhere, there might be less places that require the project service and such as well.

**Comment by Virtlink** [comment]
Please don't forget to update the documentation and add this to the changelog for the next release.

**Comment by Apanatshka** [comment]
@Gohla I just went ahead and removed the `get` methods from `ITermFactoryService` in favour of `getGeneric`. But since this basically means the same term factory is used everywhere, should we remove the service entirely and just use dependency injection for the factory?

**Comment by Gohla** [comment]
If it is fine to use the same term factory instance in all places, I guess so.

**Comment by Apanatshka** [comment]
Yeah, that should be fine. They don't have a lot of internal state at all. The constructor and string caches are in static variables, so those are shared anyway. I think using the same factory everywhere should be fine.

**Pull request merged**
